// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.SendGrid.OpenApiClient.Tsg_stats_v3.V3.Clients.Item.Stats;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.SendGrid.OpenApiClient.Tsg_stats_v3.V3.Clients.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \tsg_stats_v3\v3\clients\{client_type}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithClient_typeItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The stats property</summary>
        public global::Soenneker.SendGrid.OpenApiClient.Tsg_stats_v3.V3.Clients.Item.Stats.StatsRequestBuilder Stats
        {
            get => new global::Soenneker.SendGrid.OpenApiClient.Tsg_stats_v3.V3.Clients.Item.Stats.StatsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.SendGrid.OpenApiClient.Tsg_stats_v3.V3.Clients.Item.WithClient_typeItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithClient_typeItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tsg_stats_v3/v3/clients/{client_type}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.SendGrid.OpenApiClient.Tsg_stats_v3.V3.Clients.Item.WithClient_typeItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithClient_typeItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tsg_stats_v3/v3/clients/{client_type}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
