// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Soenneker.SendGrid.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Send
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SendPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>An object allowing you to specify how to handle unsubscribes. With SendGrid, an unsubscribe is the action an email recipient takes when they opt-out of receiving your messages. A suppression is the action you take as a sender to filter or suppress an unsubscribed address from your email send. From the perspective of the recipient, your suppression is the result of their unsubscribe. See [**Suppression Groups**](https://www.twilio.com/docs/sendgrid/api-reference/suppressions-unsubscribe-groups/create-a-new-suppression-group) for more information.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Send.SendPostRequestBody_asm? Asm { get; set; }
#nullable restore
#else
        public global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Send.SendPostRequestBody_asm Asm { get; set; }
#endif
        /// <summary>An array of objects where you can define any attachments to be included with the message. Each object contains a `content` property, which must be a Base64 encoded string of the attachment itself, and `type`, `filename`, `disposition`, and `content_id` properties that tell SendGrid how to handle the attachment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Send.SendPostRequestBody_attachments>? Attachments { get; set; }
#nullable restore
#else
        public List<global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Send.SendPostRequestBody_attachments> Attachments { get; set; }
#endif
        /// <summary>An ID representing a batch of emails to be sent at the same time. Including a `batch_id` in your request allows you to include this email in that batch. It also enables you to cancel or pause the delivery of that batch. See the [Scheduled Sends API](https://sendgrid.com/docs/api-reference/) for more information about scheduling your email.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BatchId { get; set; }
#nullable restore
#else
        public string BatchId { get; set; }
#endif
        /// <summary>An array of category names assigned to this message. Categories allow you to group messages by categories you define. Categories should be used sparingly to create general groups that are relevant to you. Categories are not meant to be used to track individual mail sends. For more granular categorization and tracking, use the `custom_args` property. A category name cannot exceed 255 characters. See [**Working with Categories**](https://docs.sendgrid.com/for-developers/sending-email/categories) for more information.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Categories { get; set; }
#nullable restore
#else
        public List<string> Categories { get; set; }
#endif
        /// <summary>An array of objects, each containing a message body&apos;s content and [MIME type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types). You must specify at least one MIME type and may include multiple. To include more than one MIME type, add an object for each type to the array.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Send.SendPostRequestBody_content>? Content { get; set; }
#nullable restore
#else
        public List<global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Send.SendPostRequestBody_content> Content { get; set; }
#endif
        /// <summary>Values that are specific to the entire send that will be carried along with the email and its activity data. Substitutions will not be made on custom arguments, so any string that is assigned to this property will be assumed to be the custom argument that you would like to be used. This parameter is overridden by `custom_args` set at the personalizations level. Total `custom_args` size may not exceed 10,000 bytes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomArgs { get; set; }
#nullable restore
#else
        public string CustomArgs { get; set; }
#endif
        /// <summary>The from property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.SendGrid.OpenApiClient.Models.MailFrom? From { get; set; }
#nullable restore
#else
        public global::Soenneker.SendGrid.OpenApiClient.Models.MailFrom From { get; set; }
#endif
        /// <summary>&quot;A collection of JSON property name and property value pairs allowing you to specify handling instructions for your email. You may not override the following headers: `x-sg-id`, `x-sg-eid`, `received`, `dkim-signature`, `Content-Type`, `Content-Transfer-Encoding`, `To`, `From`, `Subject`, `Reply-To`, `CC`, `BCC`.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Send.SendPostRequestBody_headers? Headers { get; set; }
#nullable restore
#else
        public global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Send.SendPostRequestBody_headers Headers { get; set; }
#endif
        /// <summary>The IP Pool that you would like to send this email from. IP Pools allow you to group your dedicated Twilio SendGrid IP addresses in order to have more control over your deliverability. See [**IP Pools**](https://docs.sendgrid.com/ui/account-and-settings/ip-pools) for more information.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IpPoolName { get; set; }
#nullable restore
#else
        public string IpPoolName { get; set; }
#endif
        /// <summary>A collection of different mail settings that you can use to specify how you would like this email to be handled. Mail settings provide extra functionality to your mail send. See [**Mail Settings**](https://docs.sendgrid.com/ui/account-and-settings/mail) for more information.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Send.SendPostRequestBody_mail_settings? MailSettings { get; set; }
#nullable restore
#else
        public global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Send.SendPostRequestBody_mail_settings MailSettings { get; set; }
#endif
        /// <summary>An array of messages and their metadata. Each object within the `personalizations` array can be thought of as a mail envelope—it defines who should receive an individual message and how that message should be handled. See [**Personalizations**](https://sendgrid.com/docs/for-developers/sending-email/personalizations/) for more information.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Send.SendPostRequestBody_personalizations>? Personalizations { get; set; }
#nullable restore
#else
        public List<global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Send.SendPostRequestBody_personalizations> Personalizations { get; set; }
#endif
        /// <summary>The reply_to property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.SendGrid.OpenApiClient.Models.MailTo? ReplyTo { get; set; }
#nullable restore
#else
        public global::Soenneker.SendGrid.OpenApiClient.Models.MailTo ReplyTo { get; set; }
#endif
        /// <summary>An array of recipients to whom replies will be sent. Each object in this array must contain a recipient&apos;s email address. Each object in the array may optionally contain a recipient&apos;s name. You can use either the `reply_to` property or `reply_to_list` property but not both.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.SendGrid.OpenApiClient.Models.MailTo>? ReplyToList { get; set; }
#nullable restore
#else
        public List<global::Soenneker.SendGrid.OpenApiClient.Models.MailTo> ReplyToList { get; set; }
#endif
        /// <summary>A [unix timestamp](https://en.wikipedia.org/wiki/Unix_time) allowing you to specify when your email should be sent. A send cannot be scheduled more than 72 hours in advance. This property may be overridden by the `send_at` property set at the personalizations level.</summary>
        public int? SendAt { get; set; }
        /// <summary>The global or _message level_ subject of your email. Subject lines set in personalizations objects will override this global subject line. See line length limits specified in [RFC 2822](https://www.rfc-editor.org/rfc/rfc2822#section-2.1.1) for guidance on subject line character limits.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subject { get; set; }
#nullable restore
#else
        public string Subject { get; set; }
#endif
        /// <summary>An email template ID. A template that contains a subject and content—either text or html—will override any subject and content values specified at the `personalizations` or message level. If a template ID begins with `d-`, it is a dynamic template and will work with the `dynamic_template_data` property. If the template ID does not begin with `d-`, it is a standard SendGrid template and will work with the `substitutions` property. See [**How to Send an Email with Dynamic Templates**](https://docs.sendgrid.com/ui/sending-email/how-to-send-an-email-with-dynamic-templates) for more information about working with templates.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TemplateId { get; set; }
#nullable restore
#else
        public string TemplateId { get; set; }
#endif
        /// <summary>Settings to determine how you would like to track the metrics of how your recipients interact with your email. See [**Tracking Settings**](https://docs.sendgrid.com/ui/account-and-settings/tracking) for more information.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Send.SendPostRequestBody_tracking_settings? TrackingSettings { get; set; }
#nullable restore
#else
        public global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Send.SendPostRequestBody_tracking_settings TrackingSettings { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Send.SendPostRequestBody"/> and sets the default values.
        /// </summary>
        public SendPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Send.SendPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Send.SendPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Send.SendPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "asm", n => { Asm = n.GetObjectValue<global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Send.SendPostRequestBody_asm>(global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Send.SendPostRequestBody_asm.CreateFromDiscriminatorValue); } },
                { "attachments", n => { Attachments = n.GetCollectionOfObjectValues<global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Send.SendPostRequestBody_attachments>(global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Send.SendPostRequestBody_attachments.CreateFromDiscriminatorValue)?.AsList(); } },
                { "batch_id", n => { BatchId = n.GetStringValue(); } },
                { "categories", n => { Categories = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "content", n => { Content = n.GetCollectionOfObjectValues<global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Send.SendPostRequestBody_content>(global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Send.SendPostRequestBody_content.CreateFromDiscriminatorValue)?.AsList(); } },
                { "custom_args", n => { CustomArgs = n.GetStringValue(); } },
                { "from", n => { From = n.GetObjectValue<global::Soenneker.SendGrid.OpenApiClient.Models.MailFrom>(global::Soenneker.SendGrid.OpenApiClient.Models.MailFrom.CreateFromDiscriminatorValue); } },
                { "headers", n => { Headers = n.GetObjectValue<global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Send.SendPostRequestBody_headers>(global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Send.SendPostRequestBody_headers.CreateFromDiscriminatorValue); } },
                { "ip_pool_name", n => { IpPoolName = n.GetStringValue(); } },
                { "mail_settings", n => { MailSettings = n.GetObjectValue<global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Send.SendPostRequestBody_mail_settings>(global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Send.SendPostRequestBody_mail_settings.CreateFromDiscriminatorValue); } },
                { "personalizations", n => { Personalizations = n.GetCollectionOfObjectValues<global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Send.SendPostRequestBody_personalizations>(global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Send.SendPostRequestBody_personalizations.CreateFromDiscriminatorValue)?.AsList(); } },
                { "reply_to", n => { ReplyTo = n.GetObjectValue<global::Soenneker.SendGrid.OpenApiClient.Models.MailTo>(global::Soenneker.SendGrid.OpenApiClient.Models.MailTo.CreateFromDiscriminatorValue); } },
                { "reply_to_list", n => { ReplyToList = n.GetCollectionOfObjectValues<global::Soenneker.SendGrid.OpenApiClient.Models.MailTo>(global::Soenneker.SendGrid.OpenApiClient.Models.MailTo.CreateFromDiscriminatorValue)?.AsList(); } },
                { "send_at", n => { SendAt = n.GetIntValue(); } },
                { "subject", n => { Subject = n.GetStringValue(); } },
                { "template_id", n => { TemplateId = n.GetStringValue(); } },
                { "tracking_settings", n => { TrackingSettings = n.GetObjectValue<global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Send.SendPostRequestBody_tracking_settings>(global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Send.SendPostRequestBody_tracking_settings.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Send.SendPostRequestBody_asm>("asm", Asm);
            writer.WriteCollectionOfObjectValues<global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Send.SendPostRequestBody_attachments>("attachments", Attachments);
            writer.WriteStringValue("batch_id", BatchId);
            writer.WriteCollectionOfPrimitiveValues<string>("categories", Categories);
            writer.WriteCollectionOfObjectValues<global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Send.SendPostRequestBody_content>("content", Content);
            writer.WriteStringValue("custom_args", CustomArgs);
            writer.WriteObjectValue<global::Soenneker.SendGrid.OpenApiClient.Models.MailFrom>("from", From);
            writer.WriteObjectValue<global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Send.SendPostRequestBody_headers>("headers", Headers);
            writer.WriteStringValue("ip_pool_name", IpPoolName);
            writer.WriteObjectValue<global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Send.SendPostRequestBody_mail_settings>("mail_settings", MailSettings);
            writer.WriteCollectionOfObjectValues<global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Send.SendPostRequestBody_personalizations>("personalizations", Personalizations);
            writer.WriteObjectValue<global::Soenneker.SendGrid.OpenApiClient.Models.MailTo>("reply_to", ReplyTo);
            writer.WriteCollectionOfObjectValues<global::Soenneker.SendGrid.OpenApiClient.Models.MailTo>("reply_to_list", ReplyToList);
            writer.WriteIntValue("send_at", SendAt);
            writer.WriteStringValue("subject", Subject);
            writer.WriteStringValue("template_id", TemplateId);
            writer.WriteObjectValue<global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Send.SendPostRequestBody_tracking_settings>("tracking_settings", TrackingSettings);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
