// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.SendGrid.OpenApiClient.Models;
using Soenneker.SendGrid.OpenApiClient.Tsg_account_provisioning_v3.V3.Partners.Accounts.Item.Offerings;
using Soenneker.SendGrid.OpenApiClient.Tsg_account_provisioning_v3.V3.Partners.Accounts.Item.Sso;
using Soenneker.SendGrid.OpenApiClient.Tsg_account_provisioning_v3.V3.Partners.Accounts.Item.State;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.SendGrid.OpenApiClient.Tsg_account_provisioning_v3.V3.Partners.Accounts.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \tsg_account_provisioning_v3\v3\partners\accounts\{accountID}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithAccountItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The offerings property</summary>
        public global::Soenneker.SendGrid.OpenApiClient.Tsg_account_provisioning_v3.V3.Partners.Accounts.Item.Offerings.OfferingsRequestBuilder Offerings
        {
            get => new global::Soenneker.SendGrid.OpenApiClient.Tsg_account_provisioning_v3.V3.Partners.Accounts.Item.Offerings.OfferingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sso property</summary>
        public global::Soenneker.SendGrid.OpenApiClient.Tsg_account_provisioning_v3.V3.Partners.Accounts.Item.Sso.SsoRequestBuilder Sso
        {
            get => new global::Soenneker.SendGrid.OpenApiClient.Tsg_account_provisioning_v3.V3.Partners.Accounts.Item.Sso.SsoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The state property</summary>
        public global::Soenneker.SendGrid.OpenApiClient.Tsg_account_provisioning_v3.V3.Partners.Accounts.Item.State.StateRequestBuilder State
        {
            get => new global::Soenneker.SendGrid.OpenApiClient.Tsg_account_provisioning_v3.V3.Partners.Accounts.Item.State.StateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.SendGrid.OpenApiClient.Tsg_account_provisioning_v3.V3.Partners.Accounts.Item.WithAccountItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithAccountItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tsg_account_provisioning_v3/v3/partners/accounts/{accountID}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.SendGrid.OpenApiClient.Tsg_account_provisioning_v3.V3.Partners.Accounts.Item.WithAccountItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithAccountItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tsg_account_provisioning_v3/v3/partners/accounts/{accountID}", rawUrl)
        {
        }
        /// <summary>
        /// Delete a specific account under your organization by account ID. Note that this is an **irreversible** action that does the following: - Revokes API Keys and SSO so that the account user cannot log in or access SendGrid data. - Removes all offerings and configured SendGrid resources such as dedicated IPs. - Cancels billing effective immediately.
        /// </summary>
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.SendGrid.OpenApiClient.Models.WithAccount400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.SendGrid.OpenApiClient.Models.WithAccount401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.SendGrid.OpenApiClient.Models.WithAccount403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.SendGrid.OpenApiClient.Models.WithAccount404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.SendGrid.OpenApiClient.Models.WithAccount500Error">When receiving a 500 status code</exception>
        /// <exception cref="global::Soenneker.SendGrid.OpenApiClient.Models.WithAccount502Error">When receiving a 502 status code</exception>
        /// <exception cref="global::Soenneker.SendGrid.OpenApiClient.Models.WithAccount503Error">When receiving a 503 status code</exception>
        /// <exception cref="global::Soenneker.SendGrid.OpenApiClient.Models.WithAccount504Error">When receiving a 504 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.SendGrid.OpenApiClient.Models.WithAccount400Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.SendGrid.OpenApiClient.Models.WithAccount401Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.SendGrid.OpenApiClient.Models.WithAccount403Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.SendGrid.OpenApiClient.Models.WithAccount404Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.SendGrid.OpenApiClient.Models.WithAccount500Error.CreateFromDiscriminatorValue },
                { "502", global::Soenneker.SendGrid.OpenApiClient.Models.WithAccount502Error.CreateFromDiscriminatorValue },
                { "503", global::Soenneker.SendGrid.OpenApiClient.Models.WithAccount503Error.CreateFromDiscriminatorValue },
                { "504", global::Soenneker.SendGrid.OpenApiClient.Models.WithAccount504Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Delete a specific account under your organization by account ID. Note that this is an **irreversible** action that does the following: - Revokes API Keys and SSO so that the account user cannot log in or access SendGrid data. - Removes all offerings and configured SendGrid resources such as dedicated IPs. - Cancels billing effective immediately.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.SendGrid.OpenApiClient.Tsg_account_provisioning_v3.V3.Partners.Accounts.Item.WithAccountItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.SendGrid.OpenApiClient.Tsg_account_provisioning_v3.V3.Partners.Accounts.Item.WithAccountItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.SendGrid.OpenApiClient.Tsg_account_provisioning_v3.V3.Partners.Accounts.Item.WithAccountItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
