// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.SendGrid.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AutmoationsLinkStatsResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The metadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.SendGrid.OpenApiClient.Models.LinkTrackingMetadata? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.SendGrid.OpenApiClient.Models.LinkTrackingMetadata Metadata { get; set; }
#endif
        /// <summary>The results property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.SendGrid.OpenApiClient.Models.AutmoationsLinkStatsResponse_results>? Results { get; set; }
#nullable restore
#else
        public List<global::Soenneker.SendGrid.OpenApiClient.Models.AutmoationsLinkStatsResponse_results> Results { get; set; }
#endif
        /// <summary>The total_clicks property</summary>
        public int? TotalClicks { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.SendGrid.OpenApiClient.Models.AutmoationsLinkStatsResponse"/> and sets the default values.
        /// </summary>
        public AutmoationsLinkStatsResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.SendGrid.OpenApiClient.Models.AutmoationsLinkStatsResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.SendGrid.OpenApiClient.Models.AutmoationsLinkStatsResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.SendGrid.OpenApiClient.Models.AutmoationsLinkStatsResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "_metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.SendGrid.OpenApiClient.Models.LinkTrackingMetadata>(global::Soenneker.SendGrid.OpenApiClient.Models.LinkTrackingMetadata.CreateFromDiscriminatorValue); } },
                { "results", n => { Results = n.GetCollectionOfObjectValues<global::Soenneker.SendGrid.OpenApiClient.Models.AutmoationsLinkStatsResponse_results>(global::Soenneker.SendGrid.OpenApiClient.Models.AutmoationsLinkStatsResponse_results.CreateFromDiscriminatorValue)?.AsList(); } },
                { "total_clicks", n => { TotalClicks = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.SendGrid.OpenApiClient.Models.LinkTrackingMetadata>("_metadata", Metadata);
            writer.WriteCollectionOfObjectValues<global::Soenneker.SendGrid.OpenApiClient.Models.AutmoationsLinkStatsResponse_results>("results", Results);
            writer.WriteIntValue("total_clicks", TotalClicks);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
