// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.SendGrid.OpenApiClient.Models
{
    /// <summary>
    /// Summary information for a single message matching the filter.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EmailLogsMessage : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Sender email address.This may not always be a valid email address.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FromEmail { get; set; }
#nullable restore
#else
        public string FromEmail { get; set; }
#endif
        /// <summary>Textual description for drop, bounce, deferral, or delivery event</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Reason { get; set; }
#nullable restore
#else
        public string Reason { get; set; }
#endif
        /// <summary>Unique message ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SgMessageId { get; set; }
#nullable restore
#else
        public string SgMessageId { get; set; }
#endif
        /// <summary>Timestamp when message_id was created at (ISO 8601).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SgMessageIdCreatedAt { get; set; }
#nullable restore
#else
        public string SgMessageIdCreatedAt { get; set; }
#endif
        /// <summary>&quot;**A summary of the message status based on which events have occurred.**- processed: `processed`- dropped: `drop`, `cancel_drop`- deferred: `deferred`- bounced: `bounce`- blocked: `bounce` (type=`block`)- delivered: `delivered`, `click`, `open`&quot;</summary>
        public global::Soenneker.SendGrid.OpenApiClient.Models.EmailLogsMessageStatus? Status { get; set; }
        /// <summary>Email subject line.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subject { get; set; }
#nullable restore
#else
        public string Subject { get; set; }
#endif
        /// <summary>Recipient email address</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ToEmail { get; set; }
#nullable restore
#else
        public string ToEmail { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.SendGrid.OpenApiClient.Models.EmailLogsMessage"/> and sets the default values.
        /// </summary>
        public EmailLogsMessage()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.SendGrid.OpenApiClient.Models.EmailLogsMessage"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.SendGrid.OpenApiClient.Models.EmailLogsMessage CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.SendGrid.OpenApiClient.Models.EmailLogsMessage();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "from_email", n => { FromEmail = n.GetStringValue(); } },
                { "reason", n => { Reason = n.GetStringValue(); } },
                { "sg_message_id", n => { SgMessageId = n.GetStringValue(); } },
                { "sg_message_id_created_at", n => { SgMessageIdCreatedAt = n.GetStringValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.SendGrid.OpenApiClient.Models.EmailLogsMessageStatus>(); } },
                { "subject", n => { Subject = n.GetStringValue(); } },
                { "to_email", n => { ToEmail = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("from_email", FromEmail);
            writer.WriteStringValue("reason", Reason);
            writer.WriteStringValue("sg_message_id", SgMessageId);
            writer.WriteStringValue("sg_message_id_created_at", SgMessageIdCreatedAt);
            writer.WriteEnumValue<global::Soenneker.SendGrid.OpenApiClient.Models.EmailLogsMessageStatus>("status", Status);
            writer.WriteStringValue("subject", Subject);
            writer.WriteStringValue("to_email", ToEmail);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
