// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.SendGrid.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum EventName
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "bounced")]
        #pragma warning disable CS1591
        Bounced,
        #pragma warning restore CS1591
        [EnumMember(Value = "opened")]
        #pragma warning disable CS1591
        Opened,
        #pragma warning restore CS1591
        [EnumMember(Value = "clicked")]
        #pragma warning disable CS1591
        Clicked,
        #pragma warning restore CS1591
        [EnumMember(Value = "processed")]
        #pragma warning disable CS1591
        Processed,
        #pragma warning restore CS1591
        [EnumMember(Value = "dropped")]
        #pragma warning disable CS1591
        Dropped,
        #pragma warning restore CS1591
        [EnumMember(Value = "delivered")]
        #pragma warning disable CS1591
        Delivered,
        #pragma warning restore CS1591
        [EnumMember(Value = "deferred")]
        #pragma warning disable CS1591
        Deferred,
        #pragma warning restore CS1591
        [EnumMember(Value = "spam_report")]
        #pragma warning disable CS1591
        Spam_report,
        #pragma warning restore CS1591
        [EnumMember(Value = "unsubscribe")]
        #pragma warning disable CS1591
        Unsubscribe,
        #pragma warning restore CS1591
        [EnumMember(Value = "group_unsubscribe")]
        #pragma warning disable CS1591
        Group_unsubscribe,
        #pragma warning restore CS1591
        [EnumMember(Value = "group_resubscribe")]
        #pragma warning disable CS1591
        Group_resubscribe,
        #pragma warning restore CS1591
    }
}
