// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.SendGrid.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Event11
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "unsubscribe")]
        #pragma warning disable CS1591
        Unsubscribe,
        #pragma warning restore CS1591
    }
}
