// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.SendGrid.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Generation
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "legacy")]
        #pragma warning disable CS1591
        Legacy,
        #pragma warning restore CS1591
        [EnumMember(Value = "dynamic")]
        #pragma warning disable CS1591
        Dynamic,
        #pragma warning restore CS1591
    }
}
