// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.SendGrid.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ProcessedEvent : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The ID of the ASM (Advanced Suppression Manager) group associated with the message</summary>
        public int? AsmGroupId { get; set; }
        /// <summary>Message categories</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Category { get; set; }
#nullable restore
#else
        public List<string> Category { get; set; }
#endif
        /// <summary>Custom arguments provided with the mail send request.We deviate here from the Event Webhook schema by NOT merging custom args into the top level of the object,in order to avoid collisions with system-defined fields.These are known as Custom Args in [/v3/mail/send](https://www.twilio.com/docs/sendgrid/api-reference/mail-send/mail-send)but [Unique Args](https://www.twilio.com/docs/sendgrid/for-developers/sending-email/unique-arguments) in SMTP and HTTP v2 mail send (/api/mail.send.json).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.SendGrid.OpenApiClient.Models.ProcessedEvent_custom_args? CustomArgs { get; set; }
#nullable restore
#else
        public global::Soenneker.SendGrid.OpenApiClient.Models.ProcessedEvent_custom_args CustomArgs { get; set; }
#endif
        /// <summary>Recipient email address.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>The event property</summary>
        public global::Soenneker.SendGrid.OpenApiClient.Models.Event6? Event { get; set; }
        /// <summary>Outbound IP Pool metadata</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.SendGrid.OpenApiClient.Models.OutboundIpPoolMetadata? Pool { get; set; }
#nullable restore
#else
        public global::Soenneker.SendGrid.OpenApiClient.Models.OutboundIpPoolMetadata Pool { get; set; }
#endif
        /// <summary>The Unix timestamp in seconds of when the email is scheduled to be sent.</summary>
        public long? SendAt { get; set; }
        /// <summary>SendGrid Event ID, a string that uniquely identifies the event</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SgEventId { get; set; }
#nullable restore
#else
        public string SgEventId { get; set; }
#endif
        /// <summary>SendGrid Message ID, a string that uniquely identifies the message</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SgMessageId { get; set; }
#nullable restore
#else
        public string SgMessageId { get; set; }
#endif
        /// <summary>The smtpId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SmtpId { get; set; }
#nullable restore
#else
        public string SmtpId { get; set; }
#endif
        /// <summary>Unix timestamp</summary>
        public int? Timestamp { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.SendGrid.OpenApiClient.Models.ProcessedEvent"/> and sets the default values.
        /// </summary>
        public ProcessedEvent()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.SendGrid.OpenApiClient.Models.ProcessedEvent"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.SendGrid.OpenApiClient.Models.ProcessedEvent CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.SendGrid.OpenApiClient.Models.ProcessedEvent();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "asm_group_id", n => { AsmGroupId = n.GetIntValue(); } },
                { "category", n => { Category = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "custom_args", n => { CustomArgs = n.GetObjectValue<global::Soenneker.SendGrid.OpenApiClient.Models.ProcessedEvent_custom_args>(global::Soenneker.SendGrid.OpenApiClient.Models.ProcessedEvent_custom_args.CreateFromDiscriminatorValue); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "event", n => { Event = n.GetEnumValue<global::Soenneker.SendGrid.OpenApiClient.Models.Event6>(); } },
                { "pool", n => { Pool = n.GetObjectValue<global::Soenneker.SendGrid.OpenApiClient.Models.OutboundIpPoolMetadata>(global::Soenneker.SendGrid.OpenApiClient.Models.OutboundIpPoolMetadata.CreateFromDiscriminatorValue); } },
                { "send_at", n => { SendAt = n.GetLongValue(); } },
                { "sg_event_id", n => { SgEventId = n.GetStringValue(); } },
                { "sg_message_id", n => { SgMessageId = n.GetStringValue(); } },
                { "smtp-id", n => { SmtpId = n.GetStringValue(); } },
                { "timestamp", n => { Timestamp = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("asm_group_id", AsmGroupId);
            writer.WriteCollectionOfPrimitiveValues<string>("category", Category);
            writer.WriteObjectValue<global::Soenneker.SendGrid.OpenApiClient.Models.ProcessedEvent_custom_args>("custom_args", CustomArgs);
            writer.WriteStringValue("email", Email);
            writer.WriteEnumValue<global::Soenneker.SendGrid.OpenApiClient.Models.Event6>("event", Event);
            writer.WriteObjectValue<global::Soenneker.SendGrid.OpenApiClient.Models.OutboundIpPoolMetadata>("pool", Pool);
            writer.WriteLongValue("send_at", SendAt);
            writer.WriteStringValue("sg_event_id", SgEventId);
            writer.WriteStringValue("sg_message_id", SgMessageId);
            writer.WriteStringValue("smtp-id", SmtpId);
            writer.WriteIntValue("timestamp", Timestamp);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
