// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.SendGrid.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SubuserPost : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The credit_allocation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.SendGrid.OpenApiClient.Models.SubuserPost_credit_allocation? CreditAllocation { get; set; }
#nullable restore
#else
        public global::Soenneker.SendGrid.OpenApiClient.Models.SubuserPost_credit_allocation CreditAllocation { get; set; }
#endif
        /// <summary>The email address for this subuser.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>The region property</summary>
        public global::Soenneker.SendGrid.OpenApiClient.Models.Tsg_subusers_v3_Region3? Region { get; set; }
        /// <summary>The user ID for this subuser.</summary>
        public double? UserId { get; set; }
        /// <summary>The username of the subuser.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Username { get; set; }
#nullable restore
#else
        public string Username { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.SendGrid.OpenApiClient.Models.SubuserPost"/> and sets the default values.
        /// </summary>
        public SubuserPost()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.SendGrid.OpenApiClient.Models.SubuserPost"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.SendGrid.OpenApiClient.Models.SubuserPost CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.SendGrid.OpenApiClient.Models.SubuserPost();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "credit_allocation", n => { CreditAllocation = n.GetObjectValue<global::Soenneker.SendGrid.OpenApiClient.Models.SubuserPost_credit_allocation>(global::Soenneker.SendGrid.OpenApiClient.Models.SubuserPost_credit_allocation.CreateFromDiscriminatorValue); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "region", n => { Region = n.GetEnumValue<global::Soenneker.SendGrid.OpenApiClient.Models.Tsg_subusers_v3_Region3>(); } },
                { "user_id", n => { UserId = n.GetDoubleValue(); } },
                { "username", n => { Username = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.SendGrid.OpenApiClient.Models.SubuserPost_credit_allocation>("credit_allocation", CreditAllocation);
            writer.WriteStringValue("email", Email);
            writer.WriteEnumValue<global::Soenneker.SendGrid.OpenApiClient.Models.Tsg_subusers_v3_Region3>("region", Region);
            writer.WriteDoubleValue("user_id", UserId);
            writer.WriteStringValue("username", Username);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
