// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.SendGrid.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TransactionalTemplatesTemplateLean : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The generation property</summary>
        public global::Soenneker.SendGrid.OpenApiClient.Models.Generation1? Generation { get; set; }
        /// <summary>The ID of the transactional template.</summary>
        public Guid? Id { get; set; }
        /// <summary>The name for the transactional template.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The date and time that this transactional template version was updated.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedAt { get; set; }
#nullable restore
#else
        public string UpdatedAt { get; set; }
#endif
        /// <summary>The different versions of this transactional template.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.SendGrid.OpenApiClient.Models.TransactionalTemplatesVersionOutputLean>? Versions { get; set; }
#nullable restore
#else
        public List<global::Soenneker.SendGrid.OpenApiClient.Models.TransactionalTemplatesVersionOutputLean> Versions { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.SendGrid.OpenApiClient.Models.TransactionalTemplatesTemplateLean"/> and sets the default values.
        /// </summary>
        public TransactionalTemplatesTemplateLean()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.SendGrid.OpenApiClient.Models.TransactionalTemplatesTemplateLean"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.SendGrid.OpenApiClient.Models.TransactionalTemplatesTemplateLean CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.SendGrid.OpenApiClient.Models.TransactionalTemplatesTemplateLean();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "generation", n => { Generation = n.GetEnumValue<global::Soenneker.SendGrid.OpenApiClient.Models.Generation1>(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetStringValue(); } },
                { "versions", n => { Versions = n.GetCollectionOfObjectValues<global::Soenneker.SendGrid.OpenApiClient.Models.TransactionalTemplatesVersionOutputLean>(global::Soenneker.SendGrid.OpenApiClient.Models.TransactionalTemplatesVersionOutputLean.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.SendGrid.OpenApiClient.Models.Generation1>("generation", Generation);
            writer.WriteGuidValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("updated_at", UpdatedAt);
            writer.WriteCollectionOfObjectValues<global::Soenneker.SendGrid.OpenApiClient.Models.TransactionalTemplatesVersionOutputLean>("versions", Versions);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
