// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.SendGrid.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Tsg_mc_singlesends_v3_Type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "subject")]
        #pragma warning disable CS1591
        Subject,
        #pragma warning restore CS1591
        [EnumMember(Value = "content")]
        #pragma warning disable CS1591
        Content,
        #pragma warning restore CS1591
    }
}
