// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.SendGrid.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Tsg_user_v3_ListCredit_200 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The date that your credit balance was last reset.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastReset { get; set; }
#nullable restore
#else
        public string LastReset { get; set; }
#endif
        /// <summary>The next date that your credit balance will be reset.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NextReset { get; set; }
#nullable restore
#else
        public string NextReset { get; set; }
#endif
        /// <summary>The number of overdrawn credits for your account.</summary>
        public int? Overage { get; set; }
        /// <summary>The remaining number of credits available on your account.</summary>
        public int? Remain { get; set; }
        /// <summary>The frequency at which your credit balance will be reset.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResetFrequency { get; set; }
#nullable restore
#else
        public string ResetFrequency { get; set; }
#endif
        /// <summary>The total number of credits assigned to your account.</summary>
        public int? Total { get; set; }
        /// <summary>The number of credits that you have used.</summary>
        public int? Used { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.SendGrid.OpenApiClient.Models.Tsg_user_v3_ListCredit_200"/> and sets the default values.
        /// </summary>
        public Tsg_user_v3_ListCredit_200()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.SendGrid.OpenApiClient.Models.Tsg_user_v3_ListCredit_200"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.SendGrid.OpenApiClient.Models.Tsg_user_v3_ListCredit_200 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.SendGrid.OpenApiClient.Models.Tsg_user_v3_ListCredit_200();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "last_reset", n => { LastReset = n.GetStringValue(); } },
                { "next_reset", n => { NextReset = n.GetStringValue(); } },
                { "overage", n => { Overage = n.GetIntValue(); } },
                { "remain", n => { Remain = n.GetIntValue(); } },
                { "reset_frequency", n => { ResetFrequency = n.GetStringValue(); } },
                { "total", n => { Total = n.GetIntValue(); } },
                { "used", n => { Used = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("last_reset", LastReset);
            writer.WriteStringValue("next_reset", NextReset);
            writer.WriteIntValue("overage", Overage);
            writer.WriteIntValue("remain", Remain);
            writer.WriteStringValue("reset_frequency", ResetFrequency);
            writer.WriteIntValue("total", Total);
            writer.WriteIntValue("used", Used);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
