// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.SendGrid.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Tsg_mc_custom_fields_v3_ListFieldDefinition_200 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The custom_fields property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.SendGrid.OpenApiClient.Models.CustomFieldDefinitionsResponse>? CustomFields { get; set; }
#nullable restore
#else
        public List<global::Soenneker.SendGrid.OpenApiClient.Models.CustomFieldDefinitionsResponse> CustomFields { get; set; }
#endif
        /// <summary>The metadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.SendGrid.OpenApiClient.Models.Tsg_mc_custom_fields_v3_Metadata? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.SendGrid.OpenApiClient.Models.Tsg_mc_custom_fields_v3_Metadata Metadata { get; set; }
#endif
        /// <summary>The reserved_fields property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.SendGrid.OpenApiClient.Models.ReservedFieldDefinitionsResponse_item>? ReservedFields { get; set; }
#nullable restore
#else
        public List<global::Soenneker.SendGrid.OpenApiClient.Models.ReservedFieldDefinitionsResponse_item> ReservedFields { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.SendGrid.OpenApiClient.Models.Tsg_mc_custom_fields_v3_ListFieldDefinition_200"/> and sets the default values.
        /// </summary>
        public Tsg_mc_custom_fields_v3_ListFieldDefinition_200()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.SendGrid.OpenApiClient.Models.Tsg_mc_custom_fields_v3_ListFieldDefinition_200"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.SendGrid.OpenApiClient.Models.Tsg_mc_custom_fields_v3_ListFieldDefinition_200 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.SendGrid.OpenApiClient.Models.Tsg_mc_custom_fields_v3_ListFieldDefinition_200();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "custom_fields", n => { CustomFields = n.GetCollectionOfObjectValues<global::Soenneker.SendGrid.OpenApiClient.Models.CustomFieldDefinitionsResponse>(global::Soenneker.SendGrid.OpenApiClient.Models.CustomFieldDefinitionsResponse.CreateFromDiscriminatorValue)?.AsList(); } },
                { "_metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.SendGrid.OpenApiClient.Models.Tsg_mc_custom_fields_v3_Metadata>(global::Soenneker.SendGrid.OpenApiClient.Models.Tsg_mc_custom_fields_v3_Metadata.CreateFromDiscriminatorValue); } },
                { "reserved_fields", n => { ReservedFields = n.GetCollectionOfObjectValues<global::Soenneker.SendGrid.OpenApiClient.Models.ReservedFieldDefinitionsResponse_item>(global::Soenneker.SendGrid.OpenApiClient.Models.ReservedFieldDefinitionsResponse_item.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.SendGrid.OpenApiClient.Models.CustomFieldDefinitionsResponse>("custom_fields", CustomFields);
            writer.WriteObjectValue<global::Soenneker.SendGrid.OpenApiClient.Models.Tsg_mc_custom_fields_v3_Metadata>("_metadata", Metadata);
            writer.WriteCollectionOfObjectValues<global::Soenneker.SendGrid.OpenApiClient.Models.ReservedFieldDefinitionsResponse_item>("reserved_fields", ReservedFields);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
