// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.SendGrid.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TsgLmcCampaignsV3GetCampaign200 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The categories property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Categories { get; set; }
#nullable restore
#else
        public List<string> Categories { get; set; }
#endif
        /// <summary>The custom_unsubscribe_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomUnsubscribeUrl { get; set; }
#nullable restore
#else
        public string CustomUnsubscribeUrl { get; set; }
#endif
        /// <summary>The html_content property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HtmlContent { get; set; }
#nullable restore
#else
        public string HtmlContent { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The ip_pool property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IpPool { get; set; }
#nullable restore
#else
        public string IpPool { get; set; }
#endif
        /// <summary>The list_ids property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? ListIds { get; set; }
#nullable restore
#else
        public List<int?> ListIds { get; set; }
#endif
        /// <summary>The plain_content property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PlainContent { get; set; }
#nullable restore
#else
        public string PlainContent { get; set; }
#endif
        /// <summary>The segment_ids property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? SegmentIds { get; set; }
#nullable restore
#else
        public List<int?> SegmentIds { get; set; }
#endif
        /// <summary>The sender_id property</summary>
        public int? SenderId { get; set; }
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The subject property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subject { get; set; }
#nullable restore
#else
        public string Subject { get; set; }
#endif
        /// <summary>The suppression_group_id property</summary>
        public int? SuppressionGroupId { get; set; }
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.SendGrid.OpenApiClient.Models.TsgLmcCampaignsV3GetCampaign200"/> and sets the default values.
        /// </summary>
        public TsgLmcCampaignsV3GetCampaign200()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.SendGrid.OpenApiClient.Models.TsgLmcCampaignsV3GetCampaign200"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.SendGrid.OpenApiClient.Models.TsgLmcCampaignsV3GetCampaign200 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.SendGrid.OpenApiClient.Models.TsgLmcCampaignsV3GetCampaign200();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "categories", n => { Categories = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "custom_unsubscribe_url", n => { CustomUnsubscribeUrl = n.GetStringValue(); } },
                { "html_content", n => { HtmlContent = n.GetStringValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "ip_pool", n => { IpPool = n.GetStringValue(); } },
                { "list_ids", n => { ListIds = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "plain_content", n => { PlainContent = n.GetStringValue(); } },
                { "segment_ids", n => { SegmentIds = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "sender_id", n => { SenderId = n.GetIntValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "subject", n => { Subject = n.GetStringValue(); } },
                { "suppression_group_id", n => { SuppressionGroupId = n.GetIntValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("categories", Categories);
            writer.WriteStringValue("custom_unsubscribe_url", CustomUnsubscribeUrl);
            writer.WriteStringValue("html_content", HtmlContent);
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("ip_pool", IpPool);
            writer.WriteCollectionOfPrimitiveValues<int?>("list_ids", ListIds);
            writer.WriteStringValue("plain_content", PlainContent);
            writer.WriteCollectionOfPrimitiveValues<int?>("segment_ids", SegmentIds);
            writer.WriteIntValue("sender_id", SenderId);
            writer.WriteStringValue("status", Status);
            writer.WriteStringValue("subject", Subject);
            writer.WriteIntValue("suppression_group_id", SuppressionGroupId);
            writer.WriteStringValue("title", Title);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
