// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.SendGrid.OpenApiClient.Models;
using Soenneker.SendGrid.OpenApiClient.Tsg_mc_stats_v3.V3.Marketing.Stats.Automations.Item.Links;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.SendGrid.OpenApiClient.Tsg_mc_stats_v3.V3.Marketing.Stats.Automations.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \tsg_mc_stats_v3\v3\marketing\stats\automations\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AutomationsItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The links property</summary>
        public global::Soenneker.SendGrid.OpenApiClient.Tsg_mc_stats_v3.V3.Marketing.Stats.Automations.Item.Links.LinksRequestBuilder Links
        {
            get => new global::Soenneker.SendGrid.OpenApiClient.Tsg_mc_stats_v3.V3.Marketing.Stats.Automations.Item.Links.LinksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.SendGrid.OpenApiClient.Tsg_mc_stats_v3.V3.Marketing.Stats.Automations.Item.AutomationsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AutomationsItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tsg_mc_stats_v3/v3/marketing/stats/automations/{id}{?aggregated_by*,end_date*,group_by,page_size*,page_token*,start_date*,step_ids,timezone*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.SendGrid.OpenApiClient.Tsg_mc_stats_v3.V3.Marketing.Stats.Automations.Item.AutomationsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AutomationsItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tsg_mc_stats_v3/v3/marketing/stats/automations/{id}{?aggregated_by*,end_date*,group_by,page_size*,page_token*,start_date*,step_ids,timezone*}", rawUrl)
        {
        }
        /// <summary>
        /// **This endpoint allows you to retrieve stats for a single Automation using its ID.**Multiple Automation IDs can be retrieved using the &quot;Get All Automation Stats&quot; endpoint. Once you have an ID, this endpoint will return detailed stats for the single automation specified.You may constrain the stats returned using the `start_date` and `end_date` query string parameters. You can also use the `group_by` and `aggregated_by` query string parameters to further refine the stats returned.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.SendGrid.OpenApiClient.Models.AutomationsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.SendGrid.OpenApiClient.Models.Tsg_mc_stats_v3_ErrorResponse">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.SendGrid.OpenApiClient.Models.AutomationsResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.SendGrid.OpenApiClient.Tsg_mc_stats_v3.V3.Marketing.Stats.Automations.Item.AutomationsItemRequestBuilder.AutomationsItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.SendGrid.OpenApiClient.Models.AutomationsResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.SendGrid.OpenApiClient.Tsg_mc_stats_v3.V3.Marketing.Stats.Automations.Item.AutomationsItemRequestBuilder.AutomationsItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.SendGrid.OpenApiClient.Models.Tsg_mc_stats_v3_ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.SendGrid.OpenApiClient.Models.AutomationsResponse>(requestInfo, global::Soenneker.SendGrid.OpenApiClient.Models.AutomationsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// **This endpoint allows you to retrieve stats for a single Automation using its ID.**Multiple Automation IDs can be retrieved using the &quot;Get All Automation Stats&quot; endpoint. Once you have an ID, this endpoint will return detailed stats for the single automation specified.You may constrain the stats returned using the `start_date` and `end_date` query string parameters. You can also use the `group_by` and `aggregated_by` query string parameters to further refine the stats returned.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.SendGrid.OpenApiClient.Tsg_mc_stats_v3.V3.Marketing.Stats.Automations.Item.AutomationsItemRequestBuilder.AutomationsItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.SendGrid.OpenApiClient.Tsg_mc_stats_v3.V3.Marketing.Stats.Automations.Item.AutomationsItemRequestBuilder.AutomationsItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.SendGrid.OpenApiClient.Tsg_mc_stats_v3.V3.Marketing.Stats.Automations.Item.AutomationsItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.SendGrid.OpenApiClient.Tsg_mc_stats_v3.V3.Marketing.Stats.Automations.Item.AutomationsItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.SendGrid.OpenApiClient.Tsg_mc_stats_v3.V3.Marketing.Stats.Automations.Item.AutomationsItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// **This endpoint allows you to retrieve stats for a single Automation using its ID.**Multiple Automation IDs can be retrieved using the &quot;Get All Automation Stats&quot; endpoint. Once you have an ID, this endpoint will return detailed stats for the single automation specified.You may constrain the stats returned using the `start_date` and `end_date` query string parameters. You can also use the `group_by` and `aggregated_by` query string parameters to further refine the stats returned.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AutomationsItemRequestBuilderGetQueryParameters 
        {
            /// <summary>Dictates how the stats are time-sliced. Currently, `&quot;total&quot;` and `&quot;day&quot;` are supported.</summary>
            [QueryParameter("aggregated_by")]
            public global::Soenneker.SendGrid.OpenApiClient.Models.AggregatedBy? AggregatedBy { get; set; }
            /// <summary>&quot;Format: `YYYY-MM-DD`.If this parameter is included, the stats&apos; end date is included in the search.&quot;</summary>
            [QueryParameter("end_date")]
            public Date? EndDate { get; set; }
            /// <summary>Automations can have multiple steps. Including `step_id` as a `group_by` metric allows further granularity of stats.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("group_by")]
            public global::Soenneker.SendGrid.OpenApiClient.Models.Tsg_mc_stats_v3_Items[]? GroupBy { get; set; }
#nullable restore
#else
            [QueryParameter("group_by")]
            public global::Soenneker.SendGrid.OpenApiClient.Models.Tsg_mc_stats_v3_Items[] GroupBy { get; set; }
#endif
            /// <summary>The number of elements you want returned on each page.</summary>
            [QueryParameter("page_size")]
            public int? PageSize { get; set; }
            /// <summary>The stats endpoints are paginated. To get the next page, call the passed `_metadata.next` URL. If `_metadata.prev` doesn&apos;t exist, you&apos;re at the first page. Similarly, if `_metadata.next` is not present, you&apos;re at the last page.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("page_token")]
            public string? PageToken { get; set; }
#nullable restore
#else
            [QueryParameter("page_token")]
            public string PageToken { get; set; }
#endif
            /// <summary>&quot;Format: `YYYY-MM-DD`. If this parameter is included, the stats&apos; start date is included in the search.&quot;</summary>
            [QueryParameter("start_date")]
            public Date? StartDate { get; set; }
            /// <summary>Comma-separated list of `step_ids` that you want the link stats for.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("step_ids")]
            public Guid?[]? StepIds { get; set; }
#nullable restore
#else
            [QueryParameter("step_ids")]
            public Guid?[] StepIds { get; set; }
#endif
            /// <summary>[IANA Area/Region](https://en.wikipedia.org/wiki/Tz_database#Names_of_timezones) string representing the timezone in which the stats are to be presented, e.g., &quot;America/Chicago&quot;.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("timezone")]
            public string? Timezone { get; set; }
#nullable restore
#else
            [QueryParameter("timezone")]
            public string Timezone { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
