// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.SendGrid.OpenApiClient.Models;
using Soenneker.SendGrid.OpenApiClient.Tsg_api_keys_v3.V3.Api_keys.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.SendGrid.OpenApiClient.Tsg_api_keys_v3.V3.Api_keys
{
    /// <summary>
    /// Builds and executes requests for operations under \tsg_api_keys_v3\v3\api_keys
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Api_keysRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.SendGrid.OpenApiClient.tsg_api_keys_v3.v3.api_keys.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.SendGrid.OpenApiClient.Tsg_api_keys_v3.V3.Api_keys.Item.WithApi_key_ItemRequestBuilder"/></returns>
        public global::Soenneker.SendGrid.OpenApiClient.Tsg_api_keys_v3.V3.Api_keys.Item.WithApi_key_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("api_key_id", position);
                return new global::Soenneker.SendGrid.OpenApiClient.Tsg_api_keys_v3.V3.Api_keys.Item.WithApi_key_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.SendGrid.OpenApiClient.Tsg_api_keys_v3.V3.Api_keys.Api_keysRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Api_keysRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tsg_api_keys_v3/v3/api_keys{?limit*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.SendGrid.OpenApiClient.Tsg_api_keys_v3.V3.Api_keys.Api_keysRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Api_keysRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tsg_api_keys_v3/v3/api_keys{?limit*}", rawUrl)
        {
        }
        /// <summary>
        /// **This endpoint allows you to retrieve all API Keys that belong to the authenticated user.**A successful response from this API will include all available API keys&apos; names and IDs.For security reasons, there is not a way to retrieve the key itself after it&apos;s created. If you lose your API key, you must create a new one. Only the &quot;Create API keys&quot; endpoint will return a key to you and only at the time of creation.An `api_key_id` can be used to update or delete the key, as well as retrieve the key&apos;s details, such as its scopes.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.SendGrid.OpenApiClient.Models.TsgApiKeysV3ListApiKey200"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.SendGrid.OpenApiClient.Models.TsgApiKeysV3ErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.SendGrid.OpenApiClient.Models.TsgApiKeysV3ErrorResponse">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.SendGrid.OpenApiClient.Models.TsgApiKeysV3ErrorResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.SendGrid.OpenApiClient.Models.TsgApiKeysV3ListApiKey200500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.SendGrid.OpenApiClient.Models.TsgApiKeysV3ListApiKey200?> GetAsync(Action<RequestConfiguration<global::Soenneker.SendGrid.OpenApiClient.Tsg_api_keys_v3.V3.Api_keys.Api_keysRequestBuilder.Api_keysRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.SendGrid.OpenApiClient.Models.TsgApiKeysV3ListApiKey200> GetAsync(Action<RequestConfiguration<global::Soenneker.SendGrid.OpenApiClient.Tsg_api_keys_v3.V3.Api_keys.Api_keysRequestBuilder.Api_keysRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Soenneker.SendGrid.OpenApiClient.Models.TsgApiKeysV3ErrorResponse.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.SendGrid.OpenApiClient.Models.TsgApiKeysV3ErrorResponse.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.SendGrid.OpenApiClient.Models.TsgApiKeysV3ErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.SendGrid.OpenApiClient.Models.TsgApiKeysV3ListApiKey200500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.SendGrid.OpenApiClient.Models.TsgApiKeysV3ListApiKey200>(requestInfo, global::Soenneker.SendGrid.OpenApiClient.Models.TsgApiKeysV3ListApiKey200.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// **This endpoint allows you to create a new API Key for the user.**To create your initial SendGrid API Key, you should [use the SendGrid App](https://app.sendgrid.com/settings/api_keys). Once you have created a first key with scopes to manage additional API keys, you can use this API for all other key management.A JSON request body containing a `name` property is required when making requests to this endpoint. If the number of maximum keys, 100, is reached, a `403` status will be returned.Though the `name` field is required, it does not need to be unique. A unique API key ID will be generated for each key you create and returned in the response body.It is not necessary to pass a `scopes` field to the API when creating a key, but you should be aware that omitting the `scopes` field from your request will create a key with &quot;Full Access&quot; permissions by default.See the [API Key Permissions List](https://docs.sendgrid.com/api-reference/how-to-use-the-sendgrid-v3-api/authorization) for all available scopes. An API key&apos;s scopes can be updated after creation using the &quot;Update API keys&quot; endpoint.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.SendGrid.OpenApiClient.Models.TsgApiKeysV3CreateApiKey201"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.SendGrid.OpenApiClient.Models.TsgApiKeysV3ErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.SendGrid.OpenApiClient.Models.TsgApiKeysV3ErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.SendGrid.OpenApiClient.Models.TsgApiKeysV3ErrorResponse">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.SendGrid.OpenApiClient.Models.TsgApiKeysV3ErrorResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.SendGrid.OpenApiClient.Models.TsgApiKeysV3CreateApiKey201500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.SendGrid.OpenApiClient.Models.TsgApiKeysV3CreateApiKey201?> PostAsync(global::Soenneker.SendGrid.OpenApiClient.Models.TsgApiKeysV3CreateApiKey body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.SendGrid.OpenApiClient.Models.TsgApiKeysV3CreateApiKey201> PostAsync(global::Soenneker.SendGrid.OpenApiClient.Models.TsgApiKeysV3CreateApiKey body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.SendGrid.OpenApiClient.Models.TsgApiKeysV3ErrorResponse.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.SendGrid.OpenApiClient.Models.TsgApiKeysV3ErrorResponse.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.SendGrid.OpenApiClient.Models.TsgApiKeysV3ErrorResponse.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.SendGrid.OpenApiClient.Models.TsgApiKeysV3ErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.SendGrid.OpenApiClient.Models.TsgApiKeysV3CreateApiKey201500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.SendGrid.OpenApiClient.Models.TsgApiKeysV3CreateApiKey201>(requestInfo, global::Soenneker.SendGrid.OpenApiClient.Models.TsgApiKeysV3CreateApiKey201.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// **This endpoint allows you to retrieve all API Keys that belong to the authenticated user.**A successful response from this API will include all available API keys&apos; names and IDs.For security reasons, there is not a way to retrieve the key itself after it&apos;s created. If you lose your API key, you must create a new one. Only the &quot;Create API keys&quot; endpoint will return a key to you and only at the time of creation.An `api_key_id` can be used to update or delete the key, as well as retrieve the key&apos;s details, such as its scopes.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.SendGrid.OpenApiClient.Tsg_api_keys_v3.V3.Api_keys.Api_keysRequestBuilder.Api_keysRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.SendGrid.OpenApiClient.Tsg_api_keys_v3.V3.Api_keys.Api_keysRequestBuilder.Api_keysRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// **This endpoint allows you to create a new API Key for the user.**To create your initial SendGrid API Key, you should [use the SendGrid App](https://app.sendgrid.com/settings/api_keys). Once you have created a first key with scopes to manage additional API keys, you can use this API for all other key management.A JSON request body containing a `name` property is required when making requests to this endpoint. If the number of maximum keys, 100, is reached, a `403` status will be returned.Though the `name` field is required, it does not need to be unique. A unique API key ID will be generated for each key you create and returned in the response body.It is not necessary to pass a `scopes` field to the API when creating a key, but you should be aware that omitting the `scopes` field from your request will create a key with &quot;Full Access&quot; permissions by default.See the [API Key Permissions List](https://docs.sendgrid.com/api-reference/how-to-use-the-sendgrid-v3-api/authorization) for all available scopes. An API key&apos;s scopes can be updated after creation using the &quot;Update API keys&quot; endpoint.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.SendGrid.OpenApiClient.Models.TsgApiKeysV3CreateApiKey body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.SendGrid.OpenApiClient.Models.TsgApiKeysV3CreateApiKey body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.SendGrid.OpenApiClient.Tsg_api_keys_v3.V3.Api_keys.Api_keysRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.SendGrid.OpenApiClient.Tsg_api_keys_v3.V3.Api_keys.Api_keysRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.SendGrid.OpenApiClient.Tsg_api_keys_v3.V3.Api_keys.Api_keysRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// **This endpoint allows you to retrieve all API Keys that belong to the authenticated user.**A successful response from this API will include all available API keys&apos; names and IDs.For security reasons, there is not a way to retrieve the key itself after it&apos;s created. If you lose your API key, you must create a new one. Only the &quot;Create API keys&quot; endpoint will return a key to you and only at the time of creation.An `api_key_id` can be used to update or delete the key, as well as retrieve the key&apos;s details, such as its scopes.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Api_keysRequestBuilderGetQueryParameters 
        {
            [QueryParameter("limit")]
            public int? Limit { get; set; }
        }
    }
}
#pragma warning restore CS0618
