// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.SendGrid.OpenApiClient.Tsg_email_validation_v3.V3.Validations.Email;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.SendGrid.OpenApiClient.Tsg_email_validation_v3.V3.Validations
{
    /// <summary>
    /// Builds and executes requests for operations under \tsg_email_validation_v3\v3\validations
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ValidationsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The email property</summary>
        public global::Soenneker.SendGrid.OpenApiClient.Tsg_email_validation_v3.V3.Validations.Email.EmailRequestBuilder Email
        {
            get => new global::Soenneker.SendGrid.OpenApiClient.Tsg_email_validation_v3.V3.Validations.Email.EmailRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.SendGrid.OpenApiClient.Tsg_email_validation_v3.V3.Validations.ValidationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ValidationsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tsg_email_validation_v3/v3/validations", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.SendGrid.OpenApiClient.Tsg_email_validation_v3.V3.Validations.ValidationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ValidationsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tsg_email_validation_v3/v3/validations", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
