// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.SendGrid.OpenApiClient.Models;
using Soenneker.SendGrid.OpenApiClient.Tsg_tracking_settings_v3.V3.Tracking_settings.Click;
using Soenneker.SendGrid.OpenApiClient.Tsg_tracking_settings_v3.V3.Tracking_settings.Google_analytics;
using Soenneker.SendGrid.OpenApiClient.Tsg_tracking_settings_v3.V3.Tracking_settings.Open;
using Soenneker.SendGrid.OpenApiClient.Tsg_tracking_settings_v3.V3.Tracking_settings.Subscription;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.SendGrid.OpenApiClient.Tsg_tracking_settings_v3.V3.Tracking_settings
{
    /// <summary>
    /// Builds and executes requests for operations under \tsg_tracking_settings_v3\v3\tracking_settings
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Tracking_settingsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The click property</summary>
        public global::Soenneker.SendGrid.OpenApiClient.Tsg_tracking_settings_v3.V3.Tracking_settings.Click.ClickRequestBuilder Click
        {
            get => new global::Soenneker.SendGrid.OpenApiClient.Tsg_tracking_settings_v3.V3.Tracking_settings.Click.ClickRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The google_analytics property</summary>
        public global::Soenneker.SendGrid.OpenApiClient.Tsg_tracking_settings_v3.V3.Tracking_settings.Google_analytics.Google_analyticsRequestBuilder Google_analytics
        {
            get => new global::Soenneker.SendGrid.OpenApiClient.Tsg_tracking_settings_v3.V3.Tracking_settings.Google_analytics.Google_analyticsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The open property</summary>
        public global::Soenneker.SendGrid.OpenApiClient.Tsg_tracking_settings_v3.V3.Tracking_settings.Open.OpenRequestBuilder Open
        {
            get => new global::Soenneker.SendGrid.OpenApiClient.Tsg_tracking_settings_v3.V3.Tracking_settings.Open.OpenRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The subscription property</summary>
        public global::Soenneker.SendGrid.OpenApiClient.Tsg_tracking_settings_v3.V3.Tracking_settings.Subscription.SubscriptionRequestBuilder Subscription
        {
            get => new global::Soenneker.SendGrid.OpenApiClient.Tsg_tracking_settings_v3.V3.Tracking_settings.Subscription.SubscriptionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.SendGrid.OpenApiClient.Tsg_tracking_settings_v3.V3.Tracking_settings.Tracking_settingsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Tracking_settingsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tsg_tracking_settings_v3/v3/tracking_settings", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.SendGrid.OpenApiClient.Tsg_tracking_settings_v3.V3.Tracking_settings.Tracking_settingsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Tracking_settingsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tsg_tracking_settings_v3/v3/tracking_settings", rawUrl)
        {
        }
        /// <summary>
        /// **This endpoint allows you to retrieve a list of all tracking settings on your account.**
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.SendGrid.OpenApiClient.Models.Tsg_tracking_settings_v3_ListTrackingSetting_200"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.SendGrid.OpenApiClient.Models.Tsg_tracking_settings_v3_ListTrackingSetting_200?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.SendGrid.OpenApiClient.Models.Tsg_tracking_settings_v3_ListTrackingSetting_200> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.SendGrid.OpenApiClient.Models.Tsg_tracking_settings_v3_ListTrackingSetting_200>(requestInfo, global::Soenneker.SendGrid.OpenApiClient.Models.Tsg_tracking_settings_v3_ListTrackingSetting_200.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// **This endpoint allows you to retrieve a list of all tracking settings on your account.**
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.SendGrid.OpenApiClient.Tsg_tracking_settings_v3.V3.Tracking_settings.Tracking_settingsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.SendGrid.OpenApiClient.Tsg_tracking_settings_v3.V3.Tracking_settings.Tracking_settingsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.SendGrid.OpenApiClient.Tsg_tracking_settings_v3.V3.Tracking_settings.Tracking_settingsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Tracking_settingsRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
