// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.SendGrid.OpenApiClient.Models;
using Soenneker.SendGrid.OpenApiClient.Tsg_suppressions_v3.V3.Asm.Suppressions.Global;
using Soenneker.SendGrid.OpenApiClient.Tsg_suppressions_v3.V3.Asm.Suppressions.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.SendGrid.OpenApiClient.Tsg_suppressions_v3.V3.Asm.Suppressions
{
    /// <summary>
    /// Builds and executes requests for operations under \tsg_suppressions_v3\v3\asm\suppressions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SuppressionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The global property</summary>
        public global::Soenneker.SendGrid.OpenApiClient.Tsg_suppressions_v3.V3.Asm.Suppressions.Global.GlobalRequestBuilder Global
        {
            get => new global::Soenneker.SendGrid.OpenApiClient.Tsg_suppressions_v3.V3.Asm.Suppressions.Global.GlobalRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.SendGrid.OpenApiClient.tsg_suppressions_v3.v3.asm.suppressions.item collection</summary>
        /// <param name="position">The email address that you want to search suppression groups for.</param>
        /// <returns>A <see cref="global::Soenneker.SendGrid.OpenApiClient.Tsg_suppressions_v3.V3.Asm.Suppressions.Item.WithEmailItemRequestBuilder"/></returns>
        public global::Soenneker.SendGrid.OpenApiClient.Tsg_suppressions_v3.V3.Asm.Suppressions.Item.WithEmailItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("email", position);
                return new global::Soenneker.SendGrid.OpenApiClient.Tsg_suppressions_v3.V3.Asm.Suppressions.Item.WithEmailItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.SendGrid.OpenApiClient.Tsg_suppressions_v3.V3.Asm.Suppressions.SuppressionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SuppressionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tsg_suppressions_v3/v3/asm/suppressions", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.SendGrid.OpenApiClient.Tsg_suppressions_v3.V3.Asm.Suppressions.SuppressionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SuppressionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tsg_suppressions_v3/v3/asm/suppressions", rawUrl)
        {
        }
        /// <summary>
        /// **This endpoint allows you to retrieve a list of all suppressions.**
        /// </summary>
        /// <returns>A List&lt;global::Soenneker.SendGrid.OpenApiClient.Models.TsgSuppressionsV3ListAsmSuppression200&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::Soenneker.SendGrid.OpenApiClient.Models.TsgSuppressionsV3ListAsmSuppression200>?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::Soenneker.SendGrid.OpenApiClient.Models.TsgSuppressionsV3ListAsmSuppression200>> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Soenneker.SendGrid.OpenApiClient.Models.TsgSuppressionsV3ListAsmSuppression200>(requestInfo, global::Soenneker.SendGrid.OpenApiClient.Models.TsgSuppressionsV3ListAsmSuppression200.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// **This endpoint allows you to retrieve a list of all suppressions.**
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.SendGrid.OpenApiClient.Tsg_suppressions_v3.V3.Asm.Suppressions.SuppressionsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.SendGrid.OpenApiClient.Tsg_suppressions_v3.V3.Asm.Suppressions.SuppressionsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.SendGrid.OpenApiClient.Tsg_suppressions_v3.V3.Asm.Suppressions.SuppressionsRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
