// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.SendGrid.OpenApiClient.Models;
using Soenneker.SendGrid.OpenApiClient.Tsg_mail_settings_v3.V3.Mail_settings.Address_whitelist;
using Soenneker.SendGrid.OpenApiClient.Tsg_mail_settings_v3.V3.Mail_settings.Bounce_purge;
using Soenneker.SendGrid.OpenApiClient.Tsg_mail_settings_v3.V3.Mail_settings.Footer;
using Soenneker.SendGrid.OpenApiClient.Tsg_mail_settings_v3.V3.Mail_settings.Forward_bounce;
using Soenneker.SendGrid.OpenApiClient.Tsg_mail_settings_v3.V3.Mail_settings.Forward_spam;
using Soenneker.SendGrid.OpenApiClient.Tsg_mail_settings_v3.V3.Mail_settings.Template;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.SendGrid.OpenApiClient.Tsg_mail_settings_v3.V3.Mail_settings
{
    /// <summary>
    /// Builds and executes requests for operations under \tsg_mail_settings_v3\v3\mail_settings
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Mail_settingsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The address_whitelist property</summary>
        public global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_settings_v3.V3.Mail_settings.Address_whitelist.Address_whitelistRequestBuilder Address_whitelist
        {
            get => new global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_settings_v3.V3.Mail_settings.Address_whitelist.Address_whitelistRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The bounce_purge property</summary>
        public global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_settings_v3.V3.Mail_settings.Bounce_purge.Bounce_purgeRequestBuilder Bounce_purge
        {
            get => new global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_settings_v3.V3.Mail_settings.Bounce_purge.Bounce_purgeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The footer property</summary>
        public global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_settings_v3.V3.Mail_settings.Footer.FooterRequestBuilder Footer
        {
            get => new global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_settings_v3.V3.Mail_settings.Footer.FooterRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The forward_bounce property</summary>
        public global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_settings_v3.V3.Mail_settings.Forward_bounce.Forward_bounceRequestBuilder Forward_bounce
        {
            get => new global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_settings_v3.V3.Mail_settings.Forward_bounce.Forward_bounceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The forward_spam property</summary>
        public global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_settings_v3.V3.Mail_settings.Forward_spam.Forward_spamRequestBuilder Forward_spam
        {
            get => new global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_settings_v3.V3.Mail_settings.Forward_spam.Forward_spamRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The template property</summary>
        public global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_settings_v3.V3.Mail_settings.Template.TemplateRequestBuilder Template
        {
            get => new global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_settings_v3.V3.Mail_settings.Template.TemplateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_settings_v3.V3.Mail_settings.Mail_settingsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Mail_settingsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tsg_mail_settings_v3/v3/mail_settings{?limit*,offset*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_settings_v3.V3.Mail_settings.Mail_settingsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Mail_settingsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tsg_mail_settings_v3/v3/mail_settings{?limit*,offset*}", rawUrl)
        {
        }
        /// <summary>
        /// **This endpoint allows you to retrieve a paginated list of all mail settings.**Each setting will be returned with an `enabled` status set to `true` or `false` and a short description that explains what the setting does.You can use the `limit` query parameter to set the page size. If your list contains more items than the page size permits, you can make multiple requests. Use the `offset` query parameter to control the position in the list from which to start retrieving additional items.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.SendGrid.OpenApiClient.Models.Tsg_mail_settings_v3_ListMailSetting_200"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.SendGrid.OpenApiClient.Models.Tsg_mail_settings_v3_ListMailSetting_200400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.SendGrid.OpenApiClient.Models.Tsg_mail_settings_v3_ListMailSetting_200401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.SendGrid.OpenApiClient.Models.Tsg_mail_settings_v3_ListMailSetting_200403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.SendGrid.OpenApiClient.Models.Tsg_mail_settings_v3_ListMailSetting_200404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.SendGrid.OpenApiClient.Models.Tsg_mail_settings_v3_ListMailSetting_200500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.SendGrid.OpenApiClient.Models.Tsg_mail_settings_v3_ListMailSetting_200?> GetAsync(Action<RequestConfiguration<global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_settings_v3.V3.Mail_settings.Mail_settingsRequestBuilder.Mail_settingsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.SendGrid.OpenApiClient.Models.Tsg_mail_settings_v3_ListMailSetting_200> GetAsync(Action<RequestConfiguration<global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_settings_v3.V3.Mail_settings.Mail_settingsRequestBuilder.Mail_settingsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.SendGrid.OpenApiClient.Models.Tsg_mail_settings_v3_ListMailSetting_200400Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.SendGrid.OpenApiClient.Models.Tsg_mail_settings_v3_ListMailSetting_200401Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.SendGrid.OpenApiClient.Models.Tsg_mail_settings_v3_ListMailSetting_200403Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.SendGrid.OpenApiClient.Models.Tsg_mail_settings_v3_ListMailSetting_200404Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.SendGrid.OpenApiClient.Models.Tsg_mail_settings_v3_ListMailSetting_200500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.SendGrid.OpenApiClient.Models.Tsg_mail_settings_v3_ListMailSetting_200>(requestInfo, global::Soenneker.SendGrid.OpenApiClient.Models.Tsg_mail_settings_v3_ListMailSetting_200.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// **This endpoint allows you to retrieve a paginated list of all mail settings.**Each setting will be returned with an `enabled` status set to `true` or `false` and a short description that explains what the setting does.You can use the `limit` query parameter to set the page size. If your list contains more items than the page size permits, you can make multiple requests. Use the `offset` query parameter to control the position in the list from which to start retrieving additional items.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_settings_v3.V3.Mail_settings.Mail_settingsRequestBuilder.Mail_settingsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_settings_v3.V3.Mail_settings.Mail_settingsRequestBuilder.Mail_settingsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_settings_v3.V3.Mail_settings.Mail_settingsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_settings_v3.V3.Mail_settings.Mail_settingsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_settings_v3.V3.Mail_settings.Mail_settingsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// **This endpoint allows you to retrieve a paginated list of all mail settings.**Each setting will be returned with an `enabled` status set to `true` or `false` and a short description that explains what the setting does.You can use the `limit` query parameter to set the page size. If your list contains more items than the page size permits, you can make multiple requests. Use the `offset` query parameter to control the position in the list from which to start retrieving additional items.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Mail_settingsRequestBuilderGetQueryParameters 
        {
            /// <summary>`limit` sets the page size, i.e. maximum number of items from the list to be returned for a single API request. If omitted, the default page size is used.</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>The number of items in the list to skip over before starting to retrieve the items for the requested page. The default `offset` of `0` represents the beginning of the list, i.e. the start of the first page. To request the second page of the list, set the `offset` to the page size as determined by `limit`. Use multiples of the page size as your `offset` to request further consecutive pages. E.g. assume your page size is set to `10`. An `offset` of `10` requests the second page, an `offset` of `20` requests the third page and so on, provided there are sufficiently many items in your list.</summary>
            [QueryParameter("offset")]
            public int? Offset { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Mail_settingsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_settings_v3.V3.Mail_settings.Mail_settingsRequestBuilder.Mail_settingsRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
