// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.SendGrid.OpenApiClient.Models;
using Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Batch.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Batch
{
    /// <summary>
    /// Builds and executes requests for operations under \tsg_mail_v3\v3\mail\batch
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BatchRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.SendGrid.OpenApiClient.tsg_mail_v3.v3.mail.batch.item collection</summary>
        /// <param name="position">Set this parameter to the batch ID that&apos;s associated with the mail send you want to retrieve.</param>
        /// <returns>A <see cref="global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Batch.Item.WithBatch_ItemRequestBuilder"/></returns>
        public global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Batch.Item.WithBatch_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("batch_id", position);
                return new global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Batch.Item.WithBatch_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Batch.BatchRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BatchRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tsg_mail_v3/v3/mail/batch", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Batch.BatchRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BatchRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tsg_mail_v3/v3/mail/batch", rawUrl)
        {
        }
        /// <summary>
        /// **This operation allows you to generate a new mail batch ID.**Once a batch ID is created, you can associate it with a mail send by passingit in the request body of the [Mail Send operation](https://docs.sendgrid.com/api-reference/mail-send/mail-send).This makes it possible to group multiple requests to the Mail Send operationby assigning them the same batch ID.A batch ID that&apos;s associated with a mail send can be used to access and modify the associated send. For example, you can pause or cancel a send using its batch ID. See the [Scheduled Sends API](https://www.twilio.com/docs/sendgrid/api-reference/cancel-scheduled-sends) for more information about pausing and cancelling a mail send.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.SendGrid.OpenApiClient.Models.MailBatchResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.SendGrid.OpenApiClient.Models.TsgMailV3ErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.SendGrid.OpenApiClient.Models.TsgMailV3ErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.SendGrid.OpenApiClient.Models.TsgMailV3ErrorResponse">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.SendGrid.OpenApiClient.Models.TsgMailV3ErrorResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.SendGrid.OpenApiClient.Models.TsgMailV3ErrorResponse">When receiving a 405 status code</exception>
        /// <exception cref="global::Soenneker.SendGrid.OpenApiClient.Models.TsgMailV3ErrorResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.SendGrid.OpenApiClient.Models.MailBatchResponse?> PostAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.SendGrid.OpenApiClient.Models.MailBatchResponse> PostAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.SendGrid.OpenApiClient.Models.TsgMailV3ErrorResponse.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.SendGrid.OpenApiClient.Models.TsgMailV3ErrorResponse.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.SendGrid.OpenApiClient.Models.TsgMailV3ErrorResponse.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.SendGrid.OpenApiClient.Models.TsgMailV3ErrorResponse.CreateFromDiscriminatorValue },
                { "405", global::Soenneker.SendGrid.OpenApiClient.Models.TsgMailV3ErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.SendGrid.OpenApiClient.Models.TsgMailV3ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.SendGrid.OpenApiClient.Models.MailBatchResponse>(requestInfo, global::Soenneker.SendGrid.OpenApiClient.Models.MailBatchResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// **This operation allows you to generate a new mail batch ID.**Once a batch ID is created, you can associate it with a mail send by passingit in the request body of the [Mail Send operation](https://docs.sendgrid.com/api-reference/mail-send/mail-send).This makes it possible to group multiple requests to the Mail Send operationby assigning them the same batch ID.A batch ID that&apos;s associated with a mail send can be used to access and modify the associated send. For example, you can pause or cancel a send using its batch ID. See the [Scheduled Sends API](https://www.twilio.com/docs/sendgrid/api-reference/cancel-scheduled-sends) for more information about pausing and cancelling a mail send.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Batch.BatchRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Batch.BatchRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.SendGrid.OpenApiClient.Tsg_mail_v3.V3.Mail.Batch.BatchRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
